// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzlJCm2_9I9331IXB-oMCapVwD_ms7B-I',
    appId: '1:165866806807:web:d9a52579d4bc9d17b30652',
    messagingSenderId: '165866806807',
    projectId: 'new-project-32862382',
    authDomain: 'new-project-32862382.firebaseapp.com',
    storageBucket: 'new-project-32862382.appspot.com',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3ZgWEBMCqN2QtfPUzeXOpc5QO8XA1s9E',
    appId: '1:165866806807:android:f90d28721e41aed5b30652',
    messagingSenderId: '165866806807',
    projectId: 'new-project-32862382',
    storageBucket: 'new-project-32862382.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAQ0ochuPxMJV1M8Fw0R9PacrOfkXR63M',
    appId: '1:165866806807:ios:d8a14b120ff0bd16b30652',
    messagingSenderId: '165866806807',
    projectId: 'new-project-32862382',
    storageBucket: 'new-project-32862382.appspot.com',
    iosBundleId: 'com.example.flutterCourseAug23AsyncronousProgrammingAndApiHttpRequests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAQ0ochuPxMJV1M8Fw0R9PacrOfkXR63M',
    appId: '1:165866806807:ios:96dadcb59f96b3f9b30652',
    messagingSenderId: '165866806807',
    projectId: 'new-project-32862382',
    storageBucket: 'new-project-32862382.appspot.com',
    iosBundleId: 'com.example.flutterCourseAug23AsyncronousProgrammingAndApiHttpRequests.RunnerTests',
  );
}
